apiVersion: actions.kio.kasten.io/v1alpha1
kind: RestoreAction
metadata:
  name: test-app-restore
  namespace: test-app
spec:
  subject:
    apiVersion: apps.kio.kasten.io/v1alpha1
    kind: RestorePoint
    name: scheduled-n4z5fqb84t
    namespace: test-app
  targetNamespace: test-app
  overwriteExisting: true
