apiVersion: actions.kio.kasten.io/v1alpha1
kind: RunAction
metadata:
  name: run-postgres-backup
  namespace: kasten-io
spec:
  subject:
    kind: Policy
    name: postgres-backup-policy
    namespace: kasten-io
